import { Bot, FlaskConical, TriangleAlert } from "lucide-react";
import type { AiMode } from "@/lib/ai/types";

/** Tells the user exactly how a result was produced (LLM, demo rules, or fallback). */
export function AiModeNotice({ mode, model, notice }: { mode: AiMode; model: string | null; notice: string | null }) {
  if (mode === "ai" && !notice) {
    return (
      <p className="inline-flex items-center gap-1.5 rounded-full bg-violet-50 px-2.5 py-1 text-xs font-medium text-violet-700">
        <Bot className="h-3.5 w-3.5" aria-hidden />
        Generated by {model}
      </p>
    );
  }
  const Icon = mode === "fallback" ? TriangleAlert : mode === "demo" ? FlaskConical : Bot;
  const tone =
    mode === "fallback" ? "bg-amber-50 text-amber-800 ring-amber-200" : mode === "demo" ? "bg-sky-50 text-sky-800 ring-sky-200" : "bg-violet-50 text-violet-800 ring-violet-200";
  return (
    <p role="status" className={`flex items-start gap-2 rounded-lg px-3 py-2 text-xs ring-1 ring-inset ${tone}`}>
      <Icon className="mt-0.5 h-3.5 w-3.5 shrink-0" aria-hidden />
      <span>
        {mode === "ai" && model ? <strong className="font-semibold">{model}. </strong> : null}
        {notice}
      </span>
    </p>
  );
}
